// This file will be auto-generated by Supabase CLI
// For now, we'll create manual type definitions based on our schema
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
    public: {
        Tables: {
            profiles: {
                Row: {
                    id: string;
                    username: string;
                    full_name: string | null;
                    bio: string | null;
                    avatar_url: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id: string;
                    username: string;
                    full_name?: string | null;
                    bio?: string | null;
                    avatar_url?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    username?: string;
                    full_name?: string | null;
                    bio?: string | null;
                    avatar_url?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
            };
            posts: {
                Row: {
                    id: string;
                    user_id: string;
                    content: string;
                    is_public: boolean;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    user_id: string;
                    content: string;
                    is_public?: boolean;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    user_id?: string;
                    content?: string;
                    is_public?: boolean;
                    created_at?: string;
                    updated_at?: string;
                };
            };
            post_attachments: {
                Row: {
                    id: string;
                    post_id: string;
                    file_url: string;
                    file_type: string;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    post_id: string;
                    file_url: string;
                    file_type: string;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    post_id?: string;
                    file_url?: string;
                    file_type?: string;
                    created_at?: string;
                };
            };
            post_likes: {
                Row: {
                    id: string;
                    post_id: string;
                    user_id: string;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    post_id: string;
                    user_id: string;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    post_id?: string;
                    user_id?: string;
                    created_at?: string;
                };
            };
            post_comments: {
                Row: {
                    id: string;
                    post_id: string;
                    user_id: string;
                    content: string;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    post_id: string;
                    user_id: string;
                    content: string;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    post_id?: string;
                    user_id?: string;
                    content?: string;
                    created_at?: string;
                    updated_at?: string;
                };
            };
        };
        Views: {
            [key: string]: {
                Row: Record<string, unknown>;
            };
        };
        Functions: {
            [key: string]: {
                Args: Record<string, unknown>;
                Returns: unknown;
            };
        };
        Enums: {
            [key: string]: string;
        };
    };
}

// Helper types
export type Profile = Database['public']['Tables']['profiles']['Row'];
export type ProfileInsert = Database['public']['Tables']['profiles']['Insert'];
export type ProfileUpdate = Database['public']['Tables']['profiles']['Update'];

export type Post = Database['public']['Tables']['posts']['Row'];
export type PostInsert = Database['public']['Tables']['posts']['Insert'];
export type PostUpdate = Database['public']['Tables']['posts']['Update'];

export type PostAttachment = Database['public']['Tables']['post_attachments']['Row'];
export type PostAttachmentInsert = Database['public']['Tables']['post_attachments']['Insert'];

export type PostLike = Database['public']['Tables']['post_likes']['Row'];
export type PostLikeInsert = Database['public']['Tables']['post_likes']['Insert'];

export type PostComment = Database['public']['Tables']['post_comments']['Row'];
export type PostCommentInsert = Database['public']['Tables']['post_comments']['Insert'];
export type PostCommentUpdate = Database['public']['Tables']['post_comments']['Update'];

// Extended types for joined queries
export type PostWithProfile = Post & {
    profiles: Profile;
};

export type PostWithAttachments = Post & {
    post_attachments: PostAttachment[];
};

export type PostWithAll = Post & {
    profiles: Profile;
    post_attachments: PostAttachment[];
};

export type CommentWithProfile = PostComment & {
    profiles: Profile;
};

export type PostWithInteractions = Post & {
    profiles: Profile;
    post_attachments: PostAttachment[];
    like_count: number;
    comment_count: number;
    user_has_liked: boolean;
};

// Follow types
export interface Follow {
    id: string;
    follower_id: string;
    following_id: string;
    created_at: string;
}

export interface FollowWithProfile extends Follow {
    follower?: Profile;
    following?: Profile;
}

export interface FollowCounts {
    follower_count: number;
    following_count: number;
}

export interface ProfileWithCounts extends Profile {
    follower_count: number;
    following_count: number;
    is_following?: boolean;
}
